### ISSUE TITLE
Missing README.md

### ISSUE THREAD

**Issue by stasfilin** [denisglindep/link_cutter_app#1]
I think this repository should at least contain a README.md file to explain what is the purpose of this repository :)

**Comment by denisglindep** [comment]
> I think this repository should at least contain a README.md file to explain what is the purpose of this repository :)

Hello! Oh, sorry. To be honest, I've just found out this comment.

This repository was created as one of the test-projects a long time ago) And, I guess I will delete it, or add a readme. Thank you for a remark :-)
